
run_pretty_region <- function(trait, Xtrue=T){
  source("~/Documents/PhD/Experiments/Final_QTL_mapping/Scripts/Plot_scripts/New_pretty_plot_script.r")
  out_P <- plot.pretty.region(trait, Xtrue, title="Total SNP effect")
  out_add.P <- plot.pretty.region(trait, F,P="add.P", title="Additive effect")
  out_dom.P <- plot.pretty.region(trait, F, P="dom.P", title="Dominant effect")
  total_out1 <- rbind(out_P, out_add.P)
  total_out2 <- rbind(total_out1, out_dom.P)
  write.table(total_out2, file=paste0("../results/",trait,"_results.txt"))
  
}
# only results table
# run_pretty_region <- function(trait, Xtrue=T){
#   source("~/Documents/PhD/Experiments/Final_QTL_mapping/Scripts/Plot_scripts/only_single_results_table.R")
#   out_P <- plot.pretty.region(trait, Xtrue, title="Total SNP effect")
#   out_add.P <- plot.pretty.region(trait, F,P="add.P", title="Additive effect")
#   out_dom.P <- plot.pretty.region(trait, F, P="dom.P", title="Dominant effect")
#   total_out1 <- rbind(out_P, out_add.P)
#   total_out2 <- rbind(total_out1, out_dom.P)
#   write.table(total_out2, file=paste0("../results/",trait,"_results.txt"))
# 
# }

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/otu/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/otu/")

run_pretty_region("SV1", T)
run_pretty_region("SV1")
run_pretty_region("SV2")
run_pretty_region("SV3")
run_pretty_region("SV4")
run_pretty_region("SV5")
run_pretty_region("SV6")
run_pretty_region("SV7", F)
run_pretty_region("SV9")
run_pretty_region("SV10")
run_pretty_region("SV12")
run_pretty_region("SV13")
run_pretty_region("SV14")
run_pretty_region("SV17")
run_pretty_region("SV19")
run_pretty_region("SV20")
run_pretty_region("SV21")
run_pretty_region("SV22")
run_pretty_region("SV23")
run_pretty_region("SV24")
run_pretty_region("SV25")
run_pretty_region("SV26")
run_pretty_region("SV29")
run_pretty_region("SV31")
run_pretty_region("SV32")
run_pretty_region("SV33")
run_pretty_region("SV35")
run_pretty_region("SV36")
run_pretty_region("SV38")
run_pretty_region("SV39")
run_pretty_region("SV40")
run_pretty_region("SV45")
run_pretty_region("SV47")
run_pretty_region("SV49")
run_pretty_region("SV50")
run_pretty_region("SV52")
run_pretty_region("SV54", F)
run_pretty_region("SV58")
run_pretty_region("SV60")
run_pretty_region("SV61", F)
run_pretty_region("SV63")
run_pretty_region("SV64")
run_pretty_region("SV68")
run_pretty_region("SV70", F)
run_pretty_region("SV77")
run_pretty_region("SV79")
run_pretty_region("SV82")
run_pretty_region("SV85")
run_pretty_region("SV88")
run_pretty_region("SV91")
run_pretty_region("SV95")
run_pretty_region("SV97")
run_pretty_region("SV98")
run_pretty_region("SV99")
run_pretty_region("SV100")
run_pretty_region("SV101")
run_pretty_region("SV102")
run_pretty_region("SV108")
run_pretty_region("SV109")
run_pretty_region("SV111")
run_pretty_region("SV113", F)
run_pretty_region("SV115")
run_pretty_region("SV119", F)
run_pretty_region("SV122")
run_pretty_region("SV124", F)
run_pretty_region("SV126", F)
run_pretty_region("SV133", F)
run_pretty_region("SV135", F)
run_pretty_region("SV139", F)
run_pretty_region("SV142")
run_pretty_region("SV145")
run_pretty_region("SV151", F)
run_pretty_region("SV155")
run_pretty_region("SV156", F)
run_pretty_region("SV158", F)
run_pretty_region("SV166", F)
run_pretty_region("SV169")
run_pretty_region("SV170")
run_pretty_region("SV173", F)
run_pretty_region("SV180")
run_pretty_region("SV181", F)
run_pretty_region("SV184", F)
run_pretty_region("SV197")
run_pretty_region("SV212", F)
run_pretty_region("SV216")
run_pretty_region("SV229")
run_pretty_region("SV234", F)
run_pretty_region("SV238", F)
run_pretty_region("SV243", F)
run_pretty_region("SV246", F)
run_pretty_region("SV248")
run_pretty_region("SV264", F)
run_pretty_region("SV281", F)
run_pretty_region("SV293", F)
run_pretty_region("SV370", F)
run_pretty_region("SV376", F)
run_pretty_region("SV396", F)
run_pretty_region("SV746", F)



setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/genus/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/genus/")


# Genus #####
run_pretty_region("G_Alistipes")
run_pretty_region("G_Anaerostipes")
run_pretty_region("G_Butyricicoccus")
run_pretty_region("G_Clostridium_XlVa")
run_pretty_region("G_Eisenbergiella")
run_pretty_region("G_Lactobacillus")
run_pretty_region("G_Marvinbryantia")
run_pretty_region("G_Odoribacter")
run_pretty_region("G_Paraprevotella")
run_pretty_region("G_Roseburia")
run_pretty_region("G_Staphylococcus") # super strange
run_pretty_region("G_Oscillibacter")
run_pretty_region("G_Mucispirillum")
run_pretty_region("G_Intestinimonas")
run_pretty_region("G_Hungatella")
run_pretty_region("G_Helicobacter")
run_pretty_region("G_Fusicatenibacter")
run_pretty_region("G_Bacteroides")
run_pretty_region("G_Acetatifactor")
run_pretty_region("unclassified_C_Deltaproteobacteria")
run_pretty_region("unclassified_F_Ruminococcaceae")

# FAmily ####
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/family/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/family/")
run_pretty_region("F_Bacteroidaceae")
run_pretty_region("F_Deferribacteraceae")
run_pretty_region("F_Lactobacillaceae")
run_pretty_region("F_Porphyromonadaceae")
run_pretty_region("F_Prevotellaceae")
run_pretty_region("F_Rikenellaceae")
run_pretty_region("F_Staphylococcaceae")
run_pretty_region("unclassified_P_Bacteroidetes", F) 
run_pretty_region("unclassified_O_Bacteroidales", F)
run_pretty_region("unclassified_O_Clostridiales", F)
run_pretty_region("F_Ruminococcaceae")
run_pretty_region("F_Lachnospiraceae")
run_pretty_region("F_Helicobacteraceae")

# order
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/order/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/order/")
run_pretty_region("O_Lactobacillales")
run_pretty_region("O_Clostridiales")
run_pretty_region("O_Campylobacterales")
run_pretty_region("O_Bacillales")
run_pretty_region("O_Bacteroidales")
#run_pretty_region("unclassified_P_Bacteroidetes", F)
run_pretty_region("O_Deferribacterales")


#class
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/class/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/class/")
run_pretty_region("C_Bacilli") 
run_pretty_region("C_Bacteroidia")
run_pretty_region("C_Clostridia")
run_pretty_region("C_Deferribacteres") 
run_pretty_region("C_Epsilonproteobacteria")

#phylum

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/phylum/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/phylum/")
run_pretty_region("P_Bacteroidetes") 
run_pretty_region("P_Deferribacteres") 
run_pretty_region("P_Firmicutes") 
run_pretty_region("P_Proteobacteria") 
