run_manhattan <- function(trait, Xtrue=T){
  source('~/Documents/PhD/Experiments/Final_QTL_mapping/Scripts/Plot_scripts/pretty_manhattan.r')
  dir.create(path="../manhattan_plots", showWarnings = F)
  outputdir <- "../manhattan_plots/"
  taxa <- data.frame()
  for (chr in 1:19){
    tx <- readRDS(paste0(trait, "_chr_", chr, "with_add_dom.rds"))
    taxa <- rbind(taxa, tx)
  }
  if (Xtrue){
    X_chrom <- readRDS(paste0(trait, "_chrX.rds"))
    X_chrom$chr <- "20"
    taxa_X <- dplyr::bind_rows(taxa, X_chrom)
  } else{
    taxa_X <- taxa
  }
  
  mypalette <- c("#E2709A", "#CB4577", "#BD215B", "#970F42", "#75002B") # chr color palette
  require(patchwork)
  
  p1 <-gg.manhattan(gwscan = taxa_X, SNP="marker", CHR = "chr", BP="pos", P="P",col = mypalette, title = paste0(trait, " total SNP effect"), method="bon")
  
  p2<- gg.manhattan(taxa,SNP="marker", CHR = "chr", BP="pos", P="add.P", col = mypalette, title = paste0(trait, " additive SNPs"), method="bon")
  
  
  p3<-gg.manhattan(taxa,SNP="marker", CHR = "chr", BP="pos", P="dom.P", col = mypalette, title =paste0(trait, " dominant SNPs"), method="bon")
  p <- p1 /(p2+p3)
  ggsave(paste0(outputdir, trait, ".pdf"), p, width = 12, height = 8)
  ggsave(paste0(outputdir, trait, "_total.pdf"), p1,  width = 7, height = 8)
  ggsave(paste0(outputdir, trait, "_add.pdf"), p2,  width = 7, height = 8)
  ggsave(paste0(outputdir, trait, "_dom.pdf"), p3,  width = 7, height = 8)
}


setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/otu/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/otu/")
run_manhattan("SV1")
run_manhattan("SV2")
run_manhattan("SV3")
run_manhattan("SV4")
run_manhattan("SV5")
run_manhattan("SV6")
run_manhattan("SV7", F)
run_manhattan("SV9")
run_manhattan("SV10")
run_manhattan("SV12")
run_manhattan("SV13")
run_manhattan("SV14")
run_manhattan("SV17")
run_manhattan("SV19")
run_manhattan("SV20")
run_manhattan("SV21")
run_manhattan("SV22")
run_manhattan("SV23")
run_manhattan("SV24")
run_manhattan("SV25")
run_manhattan("SV26")
run_manhattan("SV29")
run_manhattan("SV31")
run_manhattan("SV32")
run_manhattan("SV33")
run_manhattan("SV35")
run_manhattan("SV36")
run_manhattan("SV38")
run_manhattan("SV39")
run_manhattan("SV40")
run_manhattan("SV45")
run_manhattan("SV47")
run_manhattan("SV49")
run_manhattan("SV50")
run_manhattan("SV52")
run_manhattan("SV54", F)
run_manhattan("SV58")
run_manhattan("SV60")
run_manhattan("SV61", F)
run_manhattan("SV63")
run_manhattan("SV64")
run_manhattan("SV68")
run_manhattan("SV70", F)
run_manhattan("SV77")
run_manhattan("SV79")
run_manhattan("SV82")
run_manhattan("SV85")
run_manhattan("SV88")
run_manhattan("SV91")
run_manhattan("SV95")
run_manhattan("SV97")
run_manhattan("SV98")
run_manhattan("SV99")
run_manhattan("SV100")
run_manhattan("SV101")
run_manhattan("SV102")
run_manhattan("SV108")
run_manhattan("SV109")
run_manhattan("SV111")
run_manhattan("SV113", F)
run_manhattan("SV115")
run_manhattan("SV119", F)
run_manhattan("SV122")
run_manhattan("SV124", F)
run_manhattan("SV126", F)
run_manhattan("SV133", F)
run_manhattan("SV135", F)
run_manhattan("SV139", F)
run_manhattan("SV142")
run_manhattan("SV145")
run_manhattan("SV151", F)
run_manhattan("SV155")
run_manhattan("SV156", F)
run_manhattan("SV158", F)
run_manhattan("SV166", F)
run_manhattan("SV169")
run_manhattan("SV170")
run_manhattan("SV173", F)
run_manhattan("SV180")
run_manhattan("SV181", F)
run_manhattan("SV184", F)
run_manhattan("SV197")
run_manhattan("SV212", F)
run_manhattan("SV216")
run_manhattan("SV229")
run_manhattan("SV234", F)
run_manhattan("SV238", F)
run_manhattan("SV243", F)
run_manhattan("SV246", F)
run_manhattan("SV248")
run_manhattan("SV264", F)
run_manhattan("SV281", F)
run_manhattan("SV293", F)
run_manhattan("SV370", F)
run_manhattan("SV376", F)
run_manhattan("SV396", F)
run_manhattan("SV746", F)

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/genus/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/genus/")
run_manhattan("G_Acetatifactor")
run_manhattan("G_Alistipes")
run_manhattan("G_Anaerostipes")
run_manhattan("G_Bacteroides")
run_manhattan("G_Butyricicoccus")
run_manhattan("G_Clostridium_XlVa")
run_manhattan("G_Dorea")
run_manhattan("G_Eisenbergiella")
run_manhattan("G_Fusicatenibacter")
run_manhattan("G_Helicobacter")
run_manhattan("G_Hungatella")
run_manhattan("G_Intestinimonas")
run_manhattan("G_Lactobacillus")
run_manhattan("G_Marvinbryantia")
run_manhattan("G_Mucispirillum")
run_manhattan("G_Odoribacter")
run_manhattan("G_Oscillibacter")
run_manhattan("G_Paraprevotella")
run_manhattan("G_Roseburia")
run_manhattan("G_Staphylococcus")
run_manhattan("unclassified_C_Deltaproteobacteria")
run_manhattan("unclassified_F_Lachnospiraceae")
run_manhattan("unclassified_F_Porphyromonadaceae")
run_manhattan("unclassified_F_Prevotellaceae")
run_manhattan("unclassified_F_Ruminococcaceae")
run_manhattan("unclassified_F_Prevotellaceae", F)
run_manhattan("unclassified_O_Clostridiales")
run_manhattan("unclassified_O_Bacteroidales")
run_manhattan("unclassified_P_Bacteroidetes")

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/family/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/family/")
run_manhattan("F_Bacteroidaceae")
run_manhattan("F_Deferribacteraceae")
run_manhattan("F_Helicobacteraceae")
run_manhattan("F_Lachnospiraceae")
run_manhattan("F_Lactobacillaceae")
run_manhattan("F_Porphyromonadaceae")
run_manhattan("F_Prevotellaceae")
run_manhattan("F_Rikenellaceae")
run_manhattan("F_Ruminococcaceae")
run_manhattan("F_Staphylococcaceae")
run_manhattan("unclassified_O_Bacteroidales", F)
run_manhattan("unclassified_O_Clostridiales", F)


setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/order/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/order/")
run_manhattan("O_Bacillales")
run_manhattan("O_Bacteroidales")
run_manhattan("O_Campylobacterales")
run_manhattan("O_Clostridiales")
run_manhattan("O_Deferribacterales")
run_manhattan("O_Lactobacillales")

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/class/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/class/")
run_manhattan("C_Bacilli")
run_manhattan("C_Bacteroidia")
run_manhattan("C_Clostridia")
run_manhattan("C_Deferribacteres")
run_manhattan("C_Epsilonproteobacteria")

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/phylum/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/phylum/")
run_manhattan("P_Bacteroidetes")
run_manhattan("P_Deferribacteres")
run_manhattan("P_Firmicutes")
run_manhattan("P_Proteobacteria")

