run_manhattan <- function(trait, Xtrue=T, threshold=NA){
  source('~/Documents/PhD/Experiments/Final_QTL_mapping/Scripts/Plot_scripts/pretty_manhattan.r')
  dir.create(path="../manhattan_plots", showWarnings = F)
  outputdir <- "../manhattan_plots/"
  taxa <- data.frame()
  for (chr in 1:19){
    tx <- readRDS(paste0(trait, "_chr_", chr, "with_add_dom.rds"))
    taxa <- rbind(taxa, tx)
  }
  if (Xtrue){
    X_chrom <- readRDS(paste0(trait, "_chrX.rds"))
    X_chrom$chr <- "20"
    taxa_X <- dplyr::bind_rows(taxa, X_chrom)
  } else{
    taxa_X <- taxa
  }
  if (!is.na(threshold)){
    threshold <- 0.05/nrow(taxa_X)/118.2177
  }
  
  mypalette <- c("#E2709A", "#CB4577", "#BD215B", "#970F42", "#75002B") # chr color palette
  require(patchwork)
  
  p1 <-gg.manhattan(gwscan = taxa_X, SNP="marker", CHR = "chr", BP="pos", P="P",threshold=threshold, col = mypalette, title = paste0(trait, " total SNP effect"), method="bon")
  
  p2<- gg.manhattan(taxa,SNP="marker", CHR = "chr", BP="pos", P="add.P",threshold=threshold, col = mypalette, title = paste0(trait, " additive SNPs"), method="bon")
  
  
  p3<-gg.manhattan(taxa,SNP="marker", CHR = "chr", BP="pos", P="dom.P", threshold=threshold,col = mypalette, title =paste0(trait, " dominant SNPs"), method="bon")
  p <- p1 /(p2+p3)
  ggsave(paste0(outputdir, trait, ".pdf"), p, width = 12, height = 8)
  ggsave(paste0(outputdir, trait, "_total.pdf"), p1,  width = 7, height = 8)
  ggsave(paste0(outputdir, trait, "_add.pdf"), p2,  width = 7, height = 8)
  ggsave(paste0(outputdir, trait, "_dom.pdf"), p3,  width = 7, height = 8)
}


setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/otu/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/otu/")
run_manhattan("SV1", threshold = T)
run_manhattan("SV2", threshold = T)
run_manhattan("SV3", threshold = T)
run_manhattan("SV4", threshold = T)
run_manhattan("SV5", threshold = T)
run_manhattan("SV6", threshold = T)
run_manhattan("SV7", threshold = T) 
run_manhattan("SV9", threshold = T)
run_manhattan("SV10", threshold = T)
run_manhattan("SV12", threshold = T)
run_manhattan("SV13", threshold = T)
run_manhattan("SV14", threshold = T)
run_manhattan("SV17", threshold = T)
run_manhattan("SV19", threshold = T)
run_manhattan("SV20", threshold = T)
run_manhattan("SV21", threshold = T)
run_manhattan("SV22", threshold = T)
run_manhattan("SV23", threshold = T)
run_manhattan("SV24", threshold = T)
run_manhattan("SV25", threshold = T)
run_manhattan("SV26", threshold = T)
run_manhattan("SV29", threshold = T)
run_manhattan("SV31", threshold = T)
run_manhattan("SV32", threshold = T)
run_manhattan("SV33", threshold = T)
run_manhattan("SV35", threshold = T)
run_manhattan("SV36", threshold = T)
run_manhattan("SV38", threshold = T)
run_manhattan("SV39", threshold = T)
run_manhattan("SV40", threshold = T)
run_manhattan("SV45", threshold = T)
run_manhattan("SV47", threshold = T)
run_manhattan("SV49", threshold = T)
run_manhattan("SV50", threshold = T)
run_manhattan("SV52", threshold = T)
run_manhattan("SV54", threshold = T)#
run_manhattan("SV58", threshold = T)
run_manhattan("SV60", threshold = T)
run_manhattan("SV61", threshold = T)
run_manhattan("SV63", threshold = T)
run_manhattan("SV64", threshold = T)
run_manhattan("SV68", threshold = T)
run_manhattan("SV70", threshold = T)
run_manhattan("SV77", threshold = T)
run_manhattan("SV79", threshold = T)
run_manhattan("SV82", threshold = T)
run_manhattan("SV85", threshold = T)
run_manhattan("SV88", threshold = T)
run_manhattan("SV91", threshold = T)
run_manhattan("SV95", threshold = T)
run_manhattan("SV97", threshold = T)
run_manhattan("SV98", threshold = T)
run_manhattan("SV99", threshold = T)
run_manhattan("SV100", threshold = T)
run_manhattan("SV101", threshold = T)
run_manhattan("SV102", threshold = T)
run_manhattan("SV108", threshold = T)
run_manhattan("SV109", threshold = T)
run_manhattan("SV111", threshold = T)
run_manhattan("SV113", threshold = T)
run_manhattan("SV115", threshold = T)
run_manhattan("SV119", threshold = T)
run_manhattan("SV122", threshold = T)
run_manhattan("SV124", threshold = T)
run_manhattan("SV126", threshold = T)
run_manhattan("SV133", threshold = T)
run_manhattan("SV135", threshold = T)
run_manhattan("SV139", threshold = T)
run_manhattan("SV142", threshold = T)
run_manhattan("SV145", threshold = T)
run_manhattan("SV151", threshold = T)
run_manhattan("SV155", threshold = T)
run_manhattan("SV156", threshold = T)
run_manhattan("SV158", threshold = T)
run_manhattan("SV166", threshold = T)
run_manhattan("SV169", threshold = T)
run_manhattan("SV170", threshold = T)
run_manhattan("SV173", threshold = T)
run_manhattan("SV180", threshold = T)
run_manhattan("SV181", threshold = T)
run_manhattan("SV184", threshold = T)
run_manhattan("SV197", threshold = T)
run_manhattan("SV212", threshold = T)
run_manhattan("SV216", threshold = T)
run_manhattan("SV229", threshold = T)
run_manhattan("SV234", threshold = T)
run_manhattan("SV238", threshold = T)
run_manhattan("SV243", threshold = T)
run_manhattan("SV246", threshold = T)
run_manhattan("SV248", threshold = T)
run_manhattan("SV264", threshold = T)
run_manhattan("SV281", threshold = T)
run_manhattan("SV293", threshold = T)
run_manhattan("SV370", threshold = T)
run_manhattan("SV376", threshold = T)
run_manhattan("SV396", threshold = T)
run_manhattan("SV746", threshold = T)

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/genus/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/genus/")
run_manhattan("G_Acetatifactor", threshold = T)
run_manhattan("G_Alistipes", threshold = T)
run_manhattan("G_Anaerostipes", threshold = T)
run_manhattan("G_Bacteroides", threshold = T)
run_manhattan("G_Butyricicoccus", threshold = T)
run_manhattan("G_Clostridium_XlVa", threshold = T)
run_manhattan("G_Dorea", threshold = T)
run_manhattan("G_Eisenbergiella", threshold = T)
run_manhattan("G_Fusicatenibacter", threshold = T)
run_manhattan("G_Helicobacter", threshold = T)
run_manhattan("G_Hungatella", threshold = T)
run_manhattan("G_Intestinimonas", threshold = T)
run_manhattan("G_Lactobacillus", threshold = T)
run_manhattan("G_Marvinbryantia", threshold = T)
run_manhattan("G_Mucispirillum", threshold = T)
run_manhattan("G_Odoribacter", threshold = T)
run_manhattan("G_Oscillibacter", threshold = T)
run_manhattan("G_Paraprevotella", threshold = T)
run_manhattan("G_Roseburia", threshold = T)
run_manhattan("G_Staphylococcus", threshold = T)
run_manhattan("unclassified_C_Deltaproteobacteria", threshold = T)
run_manhattan("unclassified_F_Lachnospiraceae", threshold = T)
run_manhattan("unclassified_F_Porphyromonadaceae", threshold = T)
run_manhattan("unclassified_F_Prevotellaceae", threshold = T)
run_manhattan("unclassified_F_Ruminococcaceae", threshold = T)
run_manhattan("unclassified_F_Prevotellaceae", F,threshold = T)
run_manhattan("unclassified_O_Clostridiales", threshold = T)
run_manhattan("unclassified_O_Bacteroidales", threshold = T)
run_manhattan("unclassified_P_Bacteroidetes", threshold = T)

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/family/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/family/")
run_manhattan("F_Bacteroidaceae", threshold = T)
run_manhattan("F_Deferribacteraceae", threshold = T)
run_manhattan("F_Helicobacteraceae", threshold = T)
run_manhattan("F_Lachnospiraceae", threshold = T)
run_manhattan("F_Lactobacillaceae", threshold = T)
run_manhattan("F_Porphyromonadaceae", threshold = T)
run_manhattan("F_Prevotellaceae", threshold = T)
run_manhattan("F_Rikenellaceae", threshold = T)
run_manhattan("F_Ruminococcaceae", threshold = T)
run_manhattan("F_Staphylococcaceae", threshold = T)
run_manhattan("unclassified_O_Bacteroidales", F, threshold = T)
run_manhattan("unclassified_O_Clostridiales", F, threshold = T)


setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/order/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/order/")
run_manhattan("O_Bacillales", threshold = T)
run_manhattan("O_Bacteroidales", threshold = T)
run_manhattan("O_Campylobacterales", threshold = T)
run_manhattan("O_Clostridiales", threshold = T)
run_manhattan("O_Deferribacterales", threshold = T)
run_manhattan("O_Lactobacillales", threshold = T)

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/class/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/class/")
run_manhattan("C_Bacilli", threshold = T)
run_manhattan("C_Bacteroidia", threshold = T)
run_manhattan("C_Clostridia", threshold = T)
run_manhattan("C_Deferribacteres", threshold = T)
run_manhattan("C_Epsilonproteobacteria", threshold = T)

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/phylum/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/phylum/")
run_manhattan("P_Bacteroidetes", threshold = T)
run_manhattan("P_Deferribacteres", threshold = T)
run_manhattan("P_Firmicutes", threshold = T)
run_manhattan("P_Proteobacteria", threshold = T)

setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/DNA/alpha/")
setwd("~/Documents/PhD/Experiments/Final_QTL_mapping/Results/Bacterial traits/RNA/alpha/")
run_manhattan("chao1", threshold = T)
run_manhattan("shannon", threshold = T)

