# This script will clean the genotype date using Argyle and PLINK

# in R
library(argyle)
setwd("~/Documents/PhD/Experiments/QTL_mapping_results/cleaning2")

# DATA IMPORT ----
# LOAD snps data
load("../Genotype_data/GM_snps.Rdata")

#remove snps with biallelic=FALSE
snps <- GM_snps[GM_snps$is.biallelic==TRUE,] #this removes about 3000 snps 

# mismatch between marker names in geno and snps files
# replace "." with "-" in rownames and marker names
# these are markers like "B6_01-074963079-S" which got corrupted to "B6_01.074963079.S"
rownames(snps) <- gsub("\\.", "-", rownames(snps))
snps[,1] <- gsub("\\.", "-", snps[,1])

# LOAD GigaMUGA data
geno_208 <-read.beadstudio(prefix = "", in.path = "../Genotype_data/208", snps = snps, keep.intensity = TRUE)
attr(geno_208,"ped")$fid <- substr(attr(geno_208, "ped")$iid, 1,2)
geno_214 <-read.beadstudio(prefix = "", in.path = "../Genotype_data/214", snps = snps, keep.intensity = TRUE)
attr(geno_214,"ped")$fid <- substr(attr(geno_214, "ped")$iid, 1,2)
geno_207 <-read.beadstudio(prefix = "", in.path = "../Genotype_data/207", snps = snps, keep.intensity = TRUE)
attr(geno_207,"ped")$fid <- substr(attr(geno_207, "ped")$iid, 1,2)

geno_merge_208_214 <- cbind(geno_208,geno_214)

geno <- cbind(geno_merge_208_214, geno_207)

# mismatch between marker names in geno and snps files
# replace "." with "-" in rownames and marker names
# these are markers like "B6_01-074963079-S" which got corrupted to "B6_01.074963079.S"
rownames(geno) <- gsub("\\.", "-", rownames(geno))

parents <- subset(geno, iid %in% c("FSP3.02.G6.06.A.4F", "TUP3.02.G7.05.C.1M", "FSP3.02.G6.06.B.1F", "TUP3.02.G7.05.D.1M", "FSP5.01.G5.03.D.1F", "HAP1.01.G6.06.B.1M", "HAP1.01.G6.06.B.2F", "HOP3.02.G9.04.A.2M", "HAP2.01.G6.07M.B.2F", "FSP3.02.G6.06.B.2M", "HAP2.01.G6.07M.B.1F", "FSP3.02.G6.07.A.1M", "HOP3.02.G8.06.A.1F", "TUP4.02.G8.02.A.4M", "HAP2.01.G6.07M.B.1M", "HOP6.03.G7.02.C.1F", "HOP6.03.G7.05.B.1F", "HAP2.01.G6.07M.B.2M", "TUP3.02.G7.05.C.1F", "HOP6.03.G7.02.C.1M", "TUP3.02.G7.05.C.2F", "HOP6.03.G7.02.C.2M", "TUP4.02.G8.01.B.1F", "FSP5.01.G5.03.D.1M", "TUP4.02.G8.03.A.1F", "FSP5.01.G5.03.D.2M"), by="samples")
save(parents, file="parents_all_snps_geno.RData")
## this command produces files 'sample.bed', 'sample.bim' and 'sample.fam'
#geno <- recode(geno, "native")
f2<- subset(geno, fid=="HZ", by="samples")

write.plink(f2, "hybrid_f2")

# Investigate missingness per individual and per SNP and make histograms.
system("plink --bfile hybrid_f2 --missing --allow-extra-chr --chr 1-19, X,Y,M")    
# output: plink.imiss and plink.lmiss, these files show respectively the proportion of missing SNPs per individual and the proportion of missing individuals per SNP.
source("hist_miss.R")

# Delete SNPs and individuals with high levels of missingness, explanation of this and all following steps can be found in box 1 and table 1 of the article mentioned in the comments of this script.
# The following two QC commands will not remove any SNPs or individuals. However, it is good practice to start the QC with these non-stringent thresholds.  
# Delete SNPs with missingness >0.1.
system("plink --bfile hybrid_f2 --geno 0.1 --make-bed --out hybrid_f2_2 --allow-extra-chr --chr 1-19, X,Y,M")

# Delete individuals with missingness >0.1.
system("plink --bfile hybrid_f2_2 --mind 0.1 --make-bed --out hybrid_f2_3")

# Generate a plot of the MAF distribution.
system("plink --bfile hybrid_f2_3 --freq --out MAF_check")
source("MAF_check.R")

# Remove SNPs with a low MAF frequency.
system("plink --bfile hybrid_f2_3 --maf 0.05 --make-bed --out hybrid_f2_4")


####################################################
### Step 4 ###

# Delete SNPs which are not in Hardy-Weinberg equilibrium (HWE).
# Check the distribution of HWE p-values of all SNPs.

system("plink --bfile hybrid_f2_4 --hardy")
# Selecting SNPs with HWE p-value below 0.00001, required for one of the two plot generated by the next Rscript, allows to zoom in on strongly deviating SNPs. 
system("awk '{ if ($9 <0.000000001) print $0 }' plink.hwe>plinkzoomhwe.hwe")
source("hwe.R")


# This second HWE step only focusses on cases because in the controls all SNPs with a HWE p-value < hwe 1e-6 were already removed
system("plink --bfile hybrid_f2_4 --hwe 1e-10 midp --hwe-all --make-bed --out hybrid_f2_5")


# # filter on ld

system("plink --bfile hybrid_f2_5 --indep-pairwise 5 1 0.9") 
# window size of 5 SNPs
# stepsize of 1 SNPs
# pairwise ld of 0.9 

# prune the filtered data 
system("plink --bfile hybrid_f2_5 --extract plink.prune.in --make-bed --out hybrids_pruned --recode") 
# extract the markers that are NOT in linkage disequilibrium
# this keeps about 47 000 markers

############## Back to R #################
# back to argyle ####
clean_geno <-read.plink("hybrids_pruned")

save(clean_geno, file="genotypes_f2_cleaned.Rdata")
clean_geno <- recode(clean_geno,"native")
write.plink(clean_geno, "clean_f2") 

#subset snps
snps <- GM_snps[rownames(clean_geno),]

# Save complete geno and snps 
save(clean_geno, file= "clean_geno.Rdata")
save(snps, file="clean_snps.Rdata")

# LD blocks 
# with cleaned data
system("plink --bfile clean_f2 --blocks no-pheno-req")

# on all snps 
system("plink --bfile hybrid_f2 --blocks no-pheno-req --out all_snps --allow-extra-chr --chr 1-19, X,Y,M")

